### ISSUE TITLE
Needs to allow `withDecryption` option

### ISSUE THREAD

**Issue by tomharrisonjr** [poad/get-aws-ssm-parameter#490] opened 2024-09-15 23:45 UTC
Quite often, the SSM Parameter Store is used to store secrets that are encrypted, but the current version only returns encrypted values.

The SSM API allows you to pass `withDecryption` having a value `true` or `false` -- [this example in the API docs shows how](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/GetParameterCommand/).

**Comment by poad** [comment] 2024-09-16 13:29
@tomharrisonjr 
Thanks. The following Pull Requeest will address this issue.
https://github.com/poad/get-aws-ssm-parameter/pull/491

**Comment by poad** [comment] 2024-09-16 14:18
@tomharrisonjr 
A version with decryption option support is now available. v3.0.0.
Please upgrade to v3.0.0.
You may also specify v3 for the latest version of v3.

I would be happy to close the Issue once the issue is resolved.

**Comment by poad** [comment] 2024-09-27 02:02
No replies have been received, so I will close it.
If the issue is not resolved, for example, please submit a new issue linked to this one.

**Closed by poad** 2024-09-27 02:02 UTC
